### ISSUE TITLE
Self upgradable rubix-assist

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-assist#109]
Tasks to do:

- [ ] Upgrade rubix-assist by self (need to accept the version in the body)
- [ ] Give the option to do command-line installation as `rubix-edge-bios`

**Comment by NubeDev** [comment]
Can you please make sure it works without the internet

**Comment by RaiBnod** [comment]
We are not making itself upgradable, it can be failed in some cases and need to SSH again. So, to make it bulletproof:

- [x] BIOS accepts the `rubix-ui` connection
- [x] BIOS needs to have the proxy to access rubix-assist through `/ra/<path>`
- [x] Install/Upgrade `rubix-assist` same as on `rubix-edge-bios` doing `rubix-edge` install/upgrade
