### ISSUE TITLE
Add auth

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-assist#20]
@RaiBnod to decide on this

The token works for me the same as FF but its up to @RaiBnod 

in the command to start the server please make sure the auth can be disabled

There was some code but its been dsiabled

https://github.com/NubeIO/rubix-assist/blob/0d6a49a8b0d66c1c586b6182fdf4a7995738dde2/pkg/router/router.go#L51

**Comment by RaiBnod** [comment]
As `auth` needs to be controlled by the developers only:
- we need to remove that from config so users can't edit it and bypass the auth and 
- give developers that `--auth` option from the command line, so developers can add and remove it
