### ISSUE TITLE
Test/Fix System time, time zone and ntp server

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-assist#41]
see client
https://github.com/NubeIO/rubix-assist/blob/master/service/clients/edgecli/time.go

see code in edge
https://github.com/NubeIO/rubix-edge/blob/a056bb353758b915aa98842c589bb31a40287ef5/service/system/date.go#L13-L12

See also some basic code for setting an NTP server
https://github.com/NubeIO/lib-date/blob/master/datectl/ntp.go#L41

**Comment by enjuthulung** [comment]
I have tested [lib-date](https://github.com/NubeIO/lib-date) library. It seems to be working as expected. 
@NubeDev do i need to create an API for this ?
