### ISSUE TITLE
MinIO API

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-assist#54]
https://min.io/

- Add an API for min-db, this will be used for backing up data from assist and or edge
- for now just do a simple example of backing up the locations, hosts
- if you use a config file for the connection details please provide an api for updating the connection details and aslo an api for a connection status and ping

**Comment by RaiBnod** [comment]
We all agreed on using `AWS S3` for data storage. Our preliminary assumptions are:

- we create each bucket for each client & can limit the users' access to some buckets only
- we have an API for configuring the S3 bucket
- we maintain the folders as `<client_name>_<site_name>_<device_name>_<global_uuid>/<project_name>/<timestamp>/<files>`
- we have APIs to download files from edge devices & push them to the clouds
